alice:
  #build: alice/.
  image: marceloalmeida/alice_bob:alice
  command: |
    bash -c "bash -s <<EOF
    confd -backend=env -onetime;
    /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
    EOF"
  volumes:
    # replace './alice' by the correct path for Codebase
    - ./alice:/app

bob:
  #build: bob/.
  image: marceloalmeida/alice_bob:bob
  command: |
    bash -c "bash -s <<EOF
    confd -backend=env -onetime;
    /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
    EOF"
  volumes:
    # replace './bob' by the correct path for Codebase
    - ./bob:/app
